export const IS_LOADING = 'IS_LOADING'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const FORGOT_PASS_SUCCESS = 'FORGOT_PASS_SUCCESS'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'